version: '3'

networks:
  default:
    name: marquez-network

services:
  postgres:
    image: postgres:14.0
    container_name: marquez-postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=marquez
      - POSTGRES_PASSWORD=marquez
      - POSTGRES_DB=marquez
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "marquez"]
      interval: 5s
      timeout: 5s
      retries: 5

  marquez:
    image: marquezproject/marquez:0.33.0
    container_name: marquez
    environment:
      - MARQUEZ_PORT=5000
      - MARQUEZ_ADMIN_PORT=5001
      - DATABASE_URL=jdbc:postgresql://postgres:5432/marquez
      - DATABASE_USER=marquez
      - DATABASE_PASSWORD=marquez
      - DATABASE_INITIAL_DELAY=10
    ports:
      - 5002:5000
      - 5003:5001
    depends_on:
      - postgres
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5000/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    image: marquezproject/marquez-web:0.33.0
    container_name: marquez-web
    ports:
      - 3000:3000
    environment:
      - MARQUEZ_HOST=marquez
      - MARQUEZ_PORT=5000
    depends_on:
      - marquez
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
    name: marquez-postgres-data